rvm: 1.8.7
before_install:
 - git submodule update --init --recursive
notifications:
  email:
    - romain42@gmail.com
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.19
  - PUPPET_VERSION=3.0.0
